### PR TITLE
Update c61650133.lua

### PR DESCRIPTION
**Pull request by VaHReX**
Add cost string

### CODE REVIEW

**Comment by VaHReX** [comment]
Several duelists have reported errors in the card strings, some have to do with the VD and others with the .lua files, since they are not declared, as is the case of this card, which showed the string to banish 1 card from the hand instead of showing the cost to keep the card on the field.

I intend to review and correct the .lua in regards to the STRINGSID as the duelists make the reports, I hope you allow me to support you in that.

**Comment by Wind2009-Louse** [comment]
Please pull request to upstream: https://github.com/Fluorohydride/ygopro-scripts, mycard/ygopro-scripts will merge it when upstream is merged.
Thanks!

**Comment by VaHReX** [comment]
> Please pull request to upstream: https://github.com/Fluorohydride/ygopro-scripts, mycard/ygopro-scripts will merge it when upstream is merged. Thanks!

that is; should I fork that project?

**Comment by Wind2009-Louse** [comment]
You may need to fork it and create a new branch based on Fluorohydride/ygopro-scripts:master to commit change

**Pull request closed without merging**
